name = input("What is your name? ")
food = input("What is your favorite food? ")
a = input("What is your hobby? ")
b = input()
c = input()
d = input()
e = input()
f = input()
g = input()
h = input()
i = input()
j = input()
k = input()
l = input()
m = input()
n = input()
o = input()
p = input()
q = input()
r = input()
s = input()
t = input()
u = input()
v = input()
w = input()
x = input()
y = input()
z = input()

print(name + " likes " + food + " and likes to do " + a)

